-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: abstractSchemaChanges/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE hhi_location (
  hhi_location_id BIGSERIAL NOT NULL,
  hhi_location_key TEXT NOT NULL,
  hhi_location_description TEXT NOT NULL,
  PRIMARY KEY(hhi_location_id)
);

CREATE UNIQUE INDEX hhi_location_key ON hhi_location (hhi_location_key);
