-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: abstractSchemaChanges/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hhi_location (
  hhi_location_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  hhi_location_key VARBINARY(255) NOT NULL,
  hhi_location_description LONGBLOB NOT NULL,
  UNIQUE INDEX hhi_location_key (hhi_location_key),
  PRIMARY KEY(hhi_location_id)
) /*$wgDBTableOptions*/;
