-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: abstractSchemaChanges/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hhi_location (
  hhi_location_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  hhi_location_key BLOB NOT NULL, hhi_location_description BLOB NOT NULL
);

CREATE UNIQUE INDEX hhi_location_key ON /*_*/hhi_location (hhi_location_key);
